[Settings]
keywords=['controller', 'beauty']

[Umay.Settings]
port=20002
pollerize=true
umay_port=19999

[Picky.Settings]
folder='~/.config/saana/picky'

[[Picky.Picks]]
pick = 'aotabekov91/saana_plugins'
subdir = [
	'src/feh',
	'src/mpv',
	'src/xkey',
	'src/i3manager',
	]
